Replace `os.path` with `pathlib.Path`
formatc1702/WireViz pull request #246
Opened 2021-10-07 21:30 UTC by formatc1702

Closes #190.

2022-01-09 01:31 UTC, kvid requested changes
I also like the pathlib interface. Consider the change suggested by @laurierloi and a few other code alternatives.

2022-01-09 01:31 UTC, kvid commented on src/wireviz/wireviz.py
> +        file_out = file_in.parent / file_in.stem  # extension will be added by graphviz output function
This is a simpler and probably more readable equivalent:
```suggestion
        file_out = file_in.with_suffix('')  # Suffix will be added by graphviz output function
```

2022-01-09 01:31 UTC, kvid commented on src/wireviz/wireviz.py
>      if not args.output_file:
Consider swapping the `if` and the `else` statements and remove the `not`:
```suggestion
    if args.output_file:
```

2022-01-09 01:40 UTC, kvid commented on src/wireviz/wireviz.py
> +        if not Path(args.prepend_file).exists():
For some strange reason, this suggestion was not included in my review just now:
(The same argument as @laurierloi describes above also applies here.)
```suggestion
        if not Path(args.prepend_file).is_file():
```

2022-08-05 16:28 UTC, formatc1702 commented
All comments have been addressed inside #251 or are no longer relevant after 251 is applied

2022-08-05 16:29 UTC, merged